backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: 'true' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: 'false' }
      - { label: "Weight", name: "weight", widget: "number"}
      - { label: 'Body', name: 'body', widget: 'markdown' }